### ISSUE TITLE
create check for changes

### ISSUE THREAD

**Issue by AndreasAugustin** [AndreasAugustin/actions-template-sync#16]
Currently the source in `src/sync_template.sh` is pushing and creating a PR even if there are no changes.
There need to be a check so that the action is not creating a branch if not needed.

**Comment by pattacini** [comment]
Hi @AndreasAugustin 👋🏻
Thanks heaps for such a nice action ✨

I've realized that when there are no changes the action fails generating an error notification unnecessarily.
Maybe, the action may end more gracefully.

**Comment by pattacini** [comment]
@AndreasAugustin do you want me to open up a dedicated issue?

**Comment by AndreasAugustin** [comment]
@pattacini thanks for your comment. I'll reopen the issue.
Sorry for late reply.

Actual this project has been inactive for a long time and one [github action](https://github.com/AndreasAugustin/actions-template-sync/blob/main/.github/workflows/stale.yml) marked this issue as `stale` and closed it.
There are some bugs left to solve. 
Because some people are interested in this project I will try to get the first release done :relaxed:

**Comment by pattacini** [comment]
That's fantastic!

Just give you a bit of backdrop, I've landed here for a particular problem involving the GitHub Classroom as reported at https://education.github.community/t/updating-assignments-after-creation/23840/35?u=pattacini.

**Comment by AndreasAugustin** [comment]
@pattacini thanks for the backdrop.
It would be possible to use one action within the upstream repository. Also with creating a PR.
The downside is that you need to manage the repositories you want to update within the upstream repository.
Furthermore you need to find a way how to handle the secrets of those repositories so that you are able to do a PR.
One solution to do this: [secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).

Nevertheless this would be an operational overhead and hard to manage when the number of repositories is rising. It is not only that you need to manage the secrets when repositories are created, also when they are renamed,...

That's why in my opinion it makes more sense to give the responsibility to the downstream repositories.

So far I will build a fast solution for that issue which will be a workaround (hope to be able to start tomorrow). Nevertheless I want to rework the entire code base. Looking at one leftover branch I guess my plan was to do a small golang application and using the GitHub API, not sure anymore :) .

Looking at the first comments of your classroom. Maybe another hint what could also work for your cases (instead of doing forks or template clones).
There is a git feature called [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) which comes with basic git installation. That way students could also include mulit different `git submodules` into their repository.
As a Prof you could for example setup different git submodule repository and add them into one template repository. The students could clone that repository and with one shell command they are able to get the latest sources.
The downside: This git feature is not basic git usage and maybe hard for people new to git.

**Comment by pattacini** [comment]
Thanks @AndreasAugustin for getting back to this.

I actually overlooked the need for using a PAT for dealing with the downstream repos. So, I concur with you that after all the current approach gives more perks.

>So far I will build a fast solution for that issue which will be a workaround (hope to be able to start tomorrow). Nevertheless I want to rework the entire code base. Looking at one leftover branch I guess my plan was to do a small golang application and using the GitHub API, not sure anymore :) .

Sound super good 🎉
Thanks again!

Honestly, I'm not a fan of submodules and I like the way GitHub Classroom provides the scaffolding to support the courses. Thanks for the hints anyway 👍🏻

**Comment by AndreasAugustin** [comment]
@pattacini sorry that it took some time. But now that issue should be solved.
Contains also some further adjustments:

- switch from [hub](https://github.com/github/hub)  to [gh-cli](https://github.com/cli/cli)
- only doing PR if new changes are present (for now the PR will add a `..templateversionrc` to the repository containing the template HEAD short hash)
- some cleanup

Some more work is needed till I am able to do a non preview release.

**Comment by pattacini** [comment]
Great! Thanks heaps.
