### ISSUE TITLE
Refusing to allow a GitHub App to create or update workflow without workflows permission

### ISSUE THREAD

**Issue by rubencougil** [AndreasAugustin/actions-template-sync#176]
Hi,

I am getting this error when running the Action.

```
   ! [remote rejected] chore/template_sync_892045d -> chore/template_sync_892045d (refusing to allow a GitHub App 
to create or update workflow `.github/workflows/template-sync.yml` without `workflows` permission)
```

I guess is related to this

```
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

Should I tweak some config parameter somewhere? I have already a Github token generated with appropriatted `workflow` permissions.

I see these permissions list on Action build (in setup step):

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

Thank you for the help! 😅

**Comment by AndreasAugustin** [comment]
Hi @rubencougil .
Thank you for the question.
I understand that you get an AUTHZ error related running your workflow.
Furthermore (if I got you right) you manually created a github secret `GITHUB_TOKEN`.
AFAIK you do not need to create that secret manually (at least I never needed to do that 😅 ).
What you need to do: `enable github workflows`within the repository. The mentioned secret is created automatically and NOT shown within your secrets view.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Remark**
Hope this helps. If your intention is to create your own app which needs permission to run that workflow. That would be a new feature which is currently not supported (yet). Happy to get new feature requests 👍

**Comment by rubencougil** [comment]
Hi Andreas, thank you for the response. 

No, I didn't create a custom `GITHUB_TOKEN` (actually, I've tried, and it's forbidden since is reserved name 😅 ). So I'm using the one that is created automatically by the Workflow.

Also, I've went through https://docs.github.com/en/actions/security-guides/automatic-token-authentication but not able to figure out what is wrong in my case.

Question: when you say `enable github workflows`, what specific config option are you talking about? I already granted write/tead permissions to Github Actions at repo level. The repo is under a Github Organization, which also has Github Actions enabled. 🤔 

![Screenshot 2022-05-27 at 11 54 07](https://user-images.githubusercontent.com/1073799/170676706-20960090-c124-424b-83a5-719810a0d558.png)

I'm still wondering what I'm missing here. 
Thank you in advance for your help.

**Comment by rubencougil** [comment]
Oh! I just figured out what was the issue 😆  🤦‍♂️ 

Problem is changing the action workflow file itself `template-sync.yml`. 

I've changed the cron job scheduling and now the Action refuses to create a PR that tries to update that file, becuase apparently, modifying the workflow is forbidden with current `GITHUB_TOKEN` permissions. 

I'll try to figure out if it's even possible to tweak permissions to allow that. I guess can be a potential scenario to change some config param in the workflow itself.

Regards,

**Comment by AndreasAugustin** [comment]
> Oh! I just figured out what was the issue 😆 🤦‍♂️
> 
> Problem is changing the action workflow file itself `template-sync.yml`.
> 
> I've changed the cron job scheduling and now the Action refuses to create a PR that tries to update that file, becuase apparently, modifying the workflow is forbidden with current `GITHUB_TOKEN` permissions.
> 
> I'll try to figure out if it's even possible to tweak permissions to allow that. I guess can be a potential scenario to change some config param in the workflow itself.
> 
> Regards,

ah, alright. Thanks for the details. Will think about a solution to that issue.
Just for verification: You have some github actions defined within your template repository and want to change something there and provide those changes downstream to the (from template) created repositories?

**Comment by rubencougil** [comment]
yeah, that's exactly the use case.

**Comment by AndreasAugustin** [comment]
> yeah, that's exactly the use case.

thanks for claification. I need to do some research. Currently not sure if that is possible out of the box.

**Comment by youngcm2** [comment]
I figured it out. I created an App that had permissions. Then I used that token and passed it to the checkout.
![image](https://user-images.githubusercontent.com/862338/177694396-e610173b-93b9-43c2-a842-eec41b44dfbf.png)

**Comment by george-gca** [comment]
I am actually having this issue. I created a [repo](https://github.com/george-gca/dual-language-al-folio) from [this template](https://github.com/alshedivat/al-folio). The action is currently enabled, but failing with this same error:

> refusing to allow a GitHub App to create or update workflow `.github/workflows/deploy.yml` without `workflows` permission. 

![image](https://user-images.githubusercontent.com/31376482/216887745-a57073ee-0b7e-4ac1-a661-8bc78e1b21e9.png)

What am I missing here?

**Comment by AndreasAugustin** [comment]
Hi @george-gca thanks for the issue.
One hint: The current issue is already closed. Because of that it is possible that your issue won't get any attention.
Maybe it is better to open a new issue and link the current one.

Related to your question. Unfortunately your links are not working.
But maybe the answer is the same like for the others above. The issue was that in their case the workflow in the source template has changed. The change wanted to change the workflow file itself within the target repository. Such a thing is not possible.
Reading your error message it seems that you want to update the workflow `deploy`.  Maybe giving your workflow the permission to change actions is a possible solution https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs .
I guess the action write permission should be sufficient. I have not tested, but happy to get feedback.
