### ISSUE TITLE
Anyone having success using this in combination with a templating tool?

### ISSUE THREAD

**Issue by sjmiller609** [AndreasAugustin/actions-template-sync#178]
# What are we trying to do?

Thanks for maintaining a great GitHub Action. I have a question about using this action with a template formatting tool, just wondering if anyone has tips. In particular, tips around git commands or templating.

We are trying to use [Cookiecutter](https://github.com/cookiecutter/cookiecutter) to template our github template repositories, and we are also working on integrating that with this action to sync. It doesn't have to be cookiecutter, really any manner of using github templates but including a string formatting steps to replace content inside the repository, I am interested to hear your experience.

The intended behavior is for a sync PR to open when changes in the parent repository (template). The sync PR to provide updates for files that the child repository didn't touch, and for the PR to show a merge conflict on files that the child repository updated and git cannot automatically merge, which the PR reviewer / application owner can then review to their application's needs, possibly resolving merge conflicts in the open PR. I think this is how this actions-template-sync action works, but when we are trying to combine that with string formatting step is where we hit trouble.

# What problems did we face?

There are some tricky aspects, related to when the string formatting is performed - for example the template repo has a file structure like this (the curly braces literally in the file name, this is what the templating engine looks at):

```
{{ cookiecutter.project_slug }}
  dir1
     some_file.py # includes some string like {{ cookiecutter.project_slug }}, for example
  dir2
```

We are testing out the approach of a github action triggered on merge to main branch, to perform the formatting, then push it in a PR to that repository. So, an application can be created from the above github template, then you will get a PR for self-formatting. After merging that, then you get:

```
dir1 # formatted content
dir2 # formatted content
{{ cookiecutter.project_slug }}
  dir1
  dir2
```

This is working well for bootstrapping a new repository in the first place. However, we don't have this working seamlessly with the actions-template-sync yet. For example, if the child repository changes dir1/some_file.py then the template also updates this file in `{{ cookiecutter.project_slug }}/dir1/some_file.py`, it will just replace the child repository's change (I think this is because our action to perform the formatting and sync is not using the same git techniques as the actions-template-sync).

My current approach is to try a similar git approach to what is in this repository, I am working through it, but have some problems, for example the formatted file does not exist in the template repository. I still think there will be a way to get this working.

Just opening this issue because I'm curious if anyone else has had success with such an approach or might have other advice on how to get this working well, it may be a common use case for github template repositories to use a templating tool like cookiecutter.

**Comment by AndreasAugustin** [comment]
Hi @sjmiller609 ,
thanks a lot for the question.
I have no experience with such an approach you mentioned.

Reading your description I can think about the following solution:
Within your target repository you create a branch with a name like `main_template`. This will be the `UPSTREAM_BRANCH` within this repository.
When the sync action kicks in there will be an open PR from `template_sync` branch to `main_template`.
Additionally you set up a github action which will be triggered when things getting merged to `main_template`.
This github action will do your templating tool things and automatically merge to your `main` branch.
If I understand your question right, this could be a solution.

```mermaid
    gitGraph
       commit
       branch template_sync
       branch main_template
       commit
       checkout template_sync
       commit
       checkout main_template
       merge template_sync
       checkout main
       merge template_sync
       commit
```

**Comment by sjmiller609** [comment]
Thanks so much for your input, and let me give your suggestion a shot!

**Comment by sjmiller609** [comment]
This is a bit messy and I'm sure it can be simplified, but here is how we got it working in our use case (however we did not end up using this action). What I was confused about was how to handle conflicts between the child repository and the template.

Template and child update the same file, how do we handle it?
- It shows a change in the sync PR and is choosing the template’s version of the conflicting lines
- The reviewer can decide not to take a suggested change by adding commits it in the PR to undo unwanted changes
- If the reviewer adds a commit to not select this change (i.e. overwrite a change to how it was before, or merge the conflicting changes together) then future changes in the template do not re-raise the same change again in the following sync PRs
  - This includes changes in other files
  - This also includes changes in the same file that do not overlap
- If the template updates the same line again, then it is suggested again in the same way as the first time
- I think this behavior is the same as template-actions-sync action

```
name: Sync repository with template

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  sync-from-template:
    runs-on: ubuntu-latest
    steps:
      # Checkout the template repository
      - name: Checkout template
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_SYNC_TOKEN }}
          repository: # omitted in github issue comment - this is the name of our template repository
          path: template-repository
          # We need the complete git history in this repository
          fetch-depth: 0
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_SYNC_TOKEN }}
          branch: main
          path: child-repository
      - name: In the template repository, create a new branch from the commit in .templateversionrc
        id: check-template-version
        run: |
          set -xe
          cd child-repository
          # Configure git in the child repo
          git config --global user.email "github-action@actions-template-sync.noreply"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global pull.rebase false
          TEMPLATE_VERSION_FILE_NAME=".templateversionrc"
          # If we have the most recently handled version
          if [ -r ${TEMPLATE_VERSION_FILE_NAME} ]
          then
            CURRENT_TEMPLATE_GIT_HASH=$(cat ${TEMPLATE_VERSION_FILE_NAME})
            cd ../template-repository
            git checkout ${CURRENT_TEMPLATE_GIT_HASH}
            # This new branch is created from the most recently handled git commit
            # in the template
            git checkout -b template-base
            echo "::set-output name=template-version-detected::true"
          # If we don't have a most recently handled version,
          # then nothing has been handled yet.
          else
            cd ../template-repository
            # Create a commit on an empty branch as the template base
            git switch --orphan template-base
            git commit --allow-empty -m "Template base"
            echo "::set-output name=template-version-detected::false"
          fi
          # Configure git in the template repo
          git config --global user.email "github-action@actions-template-sync.noreply"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global pull.rebase false
          cd ..
          ls -ltrah
      # this action will cookiecutter-format the template-repository directory
      - name: Cookiecutter format the template repository
        if: ${{ steps.check-template-version.outputs.template-version-detected == 'true' }}
        uses: ./template-repository/.github/actions/self-initialize-cookiecutter
        with:
          repo_name: ${{ github.event.repository.name }}
          working_directory: template-repository
      - name: Commit cookiecutter formatted template
        if: ${{ steps.check-template-version.outputs.template-version-detected == 'true' }}
        run: |
          cd template-repository
          ls -ltrah
          git add --all
          git status
          git commit -m "Template base"
          ls -ltrah
          git status
          cd ..
      # At this point in the workflow, we have the template repository with a branch
      # called template-base and a commit on it. This commit will have the cookiecutter
      # formatted version of the template for the most recently handled git commit
      # in the template. Next, we want to checkout the files from the most recent commit in the template,
      # cookiecutter format them, then do another git commit. The difference between these two commits
      # is the change we want to PR into the child repository.
      - name: Update template repository to the most recent code
        id: update-template-repo-with-most-recent-code
        run: |
          set -xe
          cd template-repository
          # This sets up the template-base branch with only the code
          # from the main branch
          git checkout main
          TEMPLATE_COMMIT_HASH_MOST_RECENT=$(git log --oneline | head -n 1 | cut -d" " -f1)
          git symbolic-ref HEAD refs/heads/template-base
          git reset
          # Now we have cookiecutter template of the main branch, and we need to format it again
          cd ..
          echo "::set-output name=template-handled-commit-hash::${TEMPLATE_COMMIT_HASH_MOST_RECENT}"
      - name: Cookiecutter format template repository
        uses: ./template-repository/.github/actions/self-initialize-cookiecutter
        with:
          repo_name: ${{ github.event.repository.name }}
          working_directory: template-repository
      - name: Commit cookiecutter formatted template
        id: commit-template-additions
        run: |
          set -xe
          cd template-repository
          ls -ltrah
          git add --all
          git status
          git diff HEAD
          git commit --allow-empty -m "Template updates"
          ls -ltrah
          git status
          git log --oneline | head
          TEMPLATE_ADDITIONS_COMMIT_HASH=$(git log --oneline | head -n 1 | cut -d" " -f1)
          echo "::set-output name=template-additions-commit-hash::${TEMPLATE_ADDITIONS_COMMIT_HASH}"
          cd ..
      - name: Push template additions into the child repository template-pr branch
        id: push-template-pr
        run: |
          set -xe
          cd child-repository
          git remote add template ../template-repository
          git fetch template template-base
          git branch -D template-pr || true
          git checkout -b template-pr
          git cherry-pick --keep-redundant-commits --allow-empty -X theirs ${{ steps.commit-template-additions.outputs.template-additions-commit-hash }}
          echo ${{ steps.update-template-repo-with-most-recent-code.outputs.template-handled-commit-hash }} > .templateversionrc
          git add .templateversionrc
          git status
          git diff HEAD
          if git commit -m "Update .templateversionrc" ; then
            echo "::set-output name=update-needed::true"
            git push origin template-pr
          else
            echo "No update is needed."
            echo "::set-output name=update-needed::false"
          fi
      - name: Create Pull Request
        # step fails when PR already open
        continue-on-error: true
        if: ${{ steps.push-template-pr.outputs.update-needed  == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_SYNC_TOKEN }}
        run: |
          cd child-repository
          gh pr create --title "Template updates" --body "Please review the changes from the template, deciding which are applicable to your application(s)" --base main
```

**Comment by AndreasAugustin** [comment]
@sjmiller609  with https://github.com/AndreasAugustin/actions-template-sync/issues/220 such a functionality will be implemented. Am thinking currently about 2 options:

invoke customer defined bash scripts within the repo
enable different steps within the action
Am not able to promise any date currently.

**Comment by AndreasAugustin** [comment]
@sjmiller609 hi.
The action has now the possibility to react to hooks with a yaml file definition. Maybe that makes your use case easier to be implemented
