### ISSUE TITLE
Allow configurable PR branch names & titles

### ISSUE THREAD

**Issue by JTunis** [AndreasAugustin/actions-template-sync#186]
**Is your feature request related to a problem? Please describe.**
We have some internal conventions for branch names & PR titles, so it would be nice to make them configurable.

**Describe the solution you'd like**
Add optional `pr_title` and `pr_branch_name_prefix` input vars to the Action, where the final PR title will be `${PR_TITLE}` and the final PR branch name will be `${PR_BRANCH_NAME_PREFIX}_${NEW_TEMPLATE_GIT_HASH}`

**Describe alternatives you've considered**
We can currently modify the PR title and branch name after the PR is opened but would like to avoid this manual work.

I'm happy to make these contributions myself if permitted

**Comment by AndreasAugustin** [comment]
Hi @JTunis .

Thanks a lot for the suggestion.
I fully agree with your suggestion.

Happy to implement it.

**Comment by AndreasAugustin** [comment]
@all-contributors please add @JTunis  for ideas

**Comment by AndreasAugustin** [comment]
> 
> I'm happy to make these contributions myself if permitted

Contributions of any kind are welcome!

Happy to review your pull request 👍

**Comment by AndreasAugustin** [comment]
@JTunis thanks a bunch for the PR!

It is released now with version `v0.4.0-draft`
