### ISSUE TITLE
Fails to create PRs with spaces in PR title

### ISSUE THREAD

**Issue by JTunis** [AndreasAugustin/actions-template-sync#193]
**Describe the bug**
This currently fails to create PRs with spaces in the PR title

**To Reproduce**
Use this action to create PRs with spaces in the title (which includes the default PR title). You'll see the following error:
![Screen Shot 2022-08-26 at 2 20 41 PM](https://user-images.githubusercontent.com/11543636/186968168-92425ae6-fd12-4b11-adae-d70912a0e862.png)

**Expected behavior**
The action should successfully create a PR with the given PR title

 **Additional context**
 The PR title given to the `gh create PR` command needs to be enclosed in quotes if it contains spaces

**Comment by AndreasAugustin** [comment]
@all-contributors please add @JTunis for bug
