### ISSUE TITLE
create pull request   could not add label: 'chore' not found   

### ISSUE THREAD

**Issue by donfirst** [AndreasAugustin/actions-template-sync#207]
Check new changes
Pull template
++ echo '::group::persist template version'
persist template version
++ echo '::group::commit and push changes'
++ git add .
commit and push changes
remote: 
To https://github.com/xxxx/infra-s3
 * [new branch]      chore/template_sync_9d15891 -> chore/template_sync_9d15891
++ echo ::endgroup::
++ echo '::group::create pull request'
++ gh pr create --title 'upstream merge template repository' --body 'Merge infra-gitrepositorytemplate 9d15891' -B main -l chore,template-sync
create pull request
  could not add label: 'chore' not found
  
  
  After that have to create the pull request myself -and merge to master 
  
  
  
  
  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      token: ${{ secrets.YOUR.GITHUB_SERVICE_TOKEN  }}

  - name: actions-template-sync
    uses: AndreasAugustin/actions-template-sync@v0.4.1-draft
    with:
      source_repo_ssh_private_key: ${{ secrets.DEPLOY_KEY }}
      source_repo_path: ORG/REPONAME 
      github_token: ${{ secrets.YOUR.GITHUB_SERVICE_TOKEN}}
      upstream_branch: main # defaults to main

**Comment by AndreasAugustin** [comment]
@donfirst thanks for raising the issue.
The error message means that your repository does not have a label `chore` 
Fast fix the issue:
Either create the label https://docs.github.com/en/github-ae@latest/issues/using-labels-and-milestones-to-track-work/managing-labels
or change the labels in the workflow configuration (pr_labels) https://github.com/AndreasAugustin/actions-template-sync#configuration-parameters


Remark:
This was meant by as a feature, but I already had the feeling that this can lead to issues. I will thin about the options
- remove the feature and make labels complete optional (prefered)
- auto create the labels if they do not exist (there are also downsides to that option).

**Comment by donfirst** [comment]
Morning
Seems it helped - Thank you for providing the information

**Comment by AndreasAugustin** [comment]
Great :) nevertheless I leave this issue open and treat is as bug. The current solution is not convenient and need some adjustment as mentioned above

**Comment by AndreasAugustin** [comment]
Made the PR labels now complete optional so that the user is able to decide himself if she/he want to have them.
This makes it a bit more convenient.

Will be deployed in next release.
