### ISSUE TITLE
Support CookieCutter style template repository

### ISSUE THREAD

**Issue by fatmcgav-depop** [AndreasAugustin/actions-template-sync#218]
Hi there

Firstly thanks for the time and effort invested in this action.

**Is your feature request related to a problem? Please describe.**

We're looking at leveraging a CookieCutter style template repository ([stefanbuck.com/blog/repository-templates-meets-github-actions](https://stefanbuck.com/blog/repository-templates-meets-github-actions)) and would like to be able to "render" the target repository when trying to sync it.

Is this functionality that you'd be interested in having in this action?

**Describe the solution you'd like**
Add a boolean configuration param to "render" template repository before syncing changes.

**Describe alternatives you've considered**
None currently...

**Additional context**

**Comment by AndreasAugustin** [comment]
Hi @fatmcgav-depop .

Thanks a lot for the feature request.
I need to think about it because the CookieCutter is quite special and this this project wants to be as generic as possible.

What I can currently think of is about a kind of plugin functionality where users are able to add their own code. E.q. in the case of CookieCutter it would be possible to launch a bash script after the pull of the source repo.
Within that bash script the user would be able to add custom code.
I think that gives the freedom of the usage to the user. I need to think about some security related issues and how to add it in a convenient way.
Maybe you have some thoughts?

**Comment by fatmcgav-depop** [comment]
Hey @AndreasAugustin 

Yeh, a plugin style approach would probably be a better overall proposition, as it makes it more re-usable for other scenarios...

**Comment by AndreasAugustin** [comment]
@fatmcgav-depop with #220 such a functionality will be implemented. Am thinking currently about 2 options:

- invoke customer defined bash scripts within the repo
- enable different steps within the action

Am not able to promise any date currently.

**Comment by AndreasAugustin** [comment]
@all-contributors please add @fatmcgav-depop for idea
@all-contributors please add @AndreasAugustin for question

**Comment by AndreasAugustin** [comment]
@fatmcgav-depop sorry for super late response. I was busy with other things.

Just a short question. I am thinking about the following solution:
- users can add a yaml definition file into their target repository. 
- There they are able to define some further shell related hooks. E.q.
```yaml
phases:
  install:
   - apk add --no-cache python3 py3-pip
   - python3 -m pip install cookiecutter
 post_commit:
   - cookiecutter <whatever>
   - git commit -m "my message"
```

am not sure about the phases, I think I will start small. [docs/ARCHITECTURE.md]( https://github.com/AndreasAugustin/actions-template-sync/blob/main/docs/ARCHITECTURE.md) is a nice picture about the steps. Which one would be sufficient for your use-case? (maybe after checkout/pre commit, or do you want to have 2 commits?)

In addition am not sure how to do it permission wise. Also maybe a switch to a broader used based docker image like debian or ubuntu based would be more easy to use for other people (alpine is nice, but not broadly used). Any ideas/thoughts?

Thanks in advance for your answer.

**Comment by AndreasAugustin** [comment]
@fatmcgav-depop Hi, finally #220 is done. It is now possible to add hooks.
Please refer to the documentation `README.md`.

This should now also solve your use cases (if still needed.)

**Comment by AndreasAugustin** [comment]
Because of no answer I close the issue.
