### ISSUE TITLE
Let .templatesyncignore be inside .github folder

### ISSUE THREAD

**Issue by LuisHenri** [AndreasAugustin/actions-template-sync#249]
**Is your feature request related to a problem? Please describe.**
I like to keep my root as clean as possible. Since .templatesyncignore file is something related to a github action, I guess it could also be stored in there.

**Describe the solution you'd like**
First search for it inside .github folder, then on root. I guess a simple IF...ELSE or so on the sync_template.sh would be enough

**Comment by LuisHenri** [comment]
Perhaps same for .templateversionrc? Store it inside .github?

**Comment by AndreasAugustin** [comment]
@all-contributors please add @LuisHenri for ideas

**Comment by LuisHenri** [comment]
> Hi @LuisHenri thank you very much for the idea. Generally I like it. With a fast google I did not find a spec currently what is allowed to go into the `.github` folder. I know at least some github actions (e.q. https://github.com/marketplace/actions/labeler). This is something I would like to clarify first if this is possible , but I think it is ok :)

Hey @AndreasAugustin! Thank you for the feedback! With a quick google I also found this regarding `.github` folder: https://stackoverflow.com/questions/60507097/is-there-an-overview-of-what-can-go-into-a-github-dot-github-directory

Seems like it's a "normal" directory. Is there a way of testing any changes locally? I usually use Windows. But seems like I can test it on Docker, right?

**Comment by AndreasAugustin** [comment]
@LuisHenri about testing locally. Yes there are docker images available:

- https://hub.docker.com/repository/docker/andyaugustin/actions-template-sync
- https://github.com/AndreasAugustin/actions-template-sync/pkgs/container/actions-template-sync

But it lacks documentation #254 
Another option is that you just use the plain script `src/sync_template.sh`  or also possible inside `src/entrypoint.sh`.
Related to the tests you want to do maybe that is a better option. (you can comment inside the script). In the end the docker container will also just call that script :)

**Comment by AndreasAugustin** [comment]
@LuisHenri I did not find any conventions or rules about the usage of  `.github/` folder. So lets go for the mentioned solution.

For the algorithm: lets give the `.github/` folder more weight. That means that we will first search in the `.github/` folder for `.templateversionrc` and `.templatesyncignore` files and use them if they are present. If one of the files is not present, we search this file in the root.
