### ISSUE TITLE
Typo in variable inside sync_template.sh

### ISSUE THREAD

**Issue by LuisHenri** [AndreasAugustin/actions-template-sync#267]
**Describe the bug**
Seems like I forgot to change some variable names on my last PR (sorry).

**To Reproduce**

1. Go to [sync_template.sh](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L59)

**Expected behavior**
It should be `TEMPLATE_SYNC_IGNORE_FILE_PATH` instead of `TEMPLATE_SYNC_IGNORE_FILE_NAME`

**Screenshots**
![image](https://user-images.githubusercontent.com/44511825/210115328-76669cba-557b-4bec-b81f-9fefc0a574a9.png)
![image](https://user-images.githubusercontent.com/44511825/210115340-41f1e6a1-4e3e-4f0e-9a93-c49d93e717c8.png)

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
Regarding PR #252

**Comment by AndreasAugustin** [comment]
Thanks for the fix. Seems I did not careful check last PR :)
I will think about adding a test for this case.

**Comment by LuisHenri** [comment]
@AndreasAugustin I also just forgot to change the IF order (sorry again)
#269
