### ISSUE TITLE
[Question] Push individual commits

### ISSUE THREAD

**Issue by george-gca** [AndreasAugustin/actions-template-sync#316]
I am currently using this action, and it is working great! But I realized that it doesn't apply individual commits from the template repo, it applies all the modifications as a single commit instead.

Is there a way to fetch and apply the modifications as individual commits? This way it is easier to keep track of the changes and keeps the commit tree similar to the template repo.

**Comment by AndreasAugustin** [comment]
Hi @george-gca most likely that line is the reason for discussion: `src/sync_template.sh`
![Screenshot 2023-02-14 at 16 38 55](https://user-images.githubusercontent.com/8027933/218785479-9098acaa-a8b6-41b0-8f4f-3c79bef7565f.png)

squashing is a nice option, have thought about making it optional. The thing is that you most likely don't keep a linear history without squashing the commit.

**Comment by george-gca** [comment]
Even if the template repo keeps a linear history?

**Comment by AndreasAugustin** [comment]
Am quite sure, if you go on working on the target repo and on the source repo, there will be commits on both and most likely overlapping in terms of time.
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

But we can add an option ofc. It can also be squashed at the PR level. Lets test it out :)

You can play around with the available docker container or locally with the scripts themself. Also happy about a PR with the option

**Comment by george-gca** [comment]
How can I create a testbed for this?

Also, what about a rebase option?

**Comment by AndreasAugustin** [comment]
> How can I create a testbed for this?
> 
> Also, what about a rebase option?

also a possibility. One disadvantage is that it is possible that you need to do a lot of conflict resolving. But maybe also a nice option to add. So far there was no request for that. Do you have a solution in mind?
For me currently a squash is good enough, but ofc if the community has a request, am happy to implement it.

**Comment by AndreasAugustin** [comment]
@george-gca with new release `v0.8.0` you have a new configuration parameter:
`git_remote_pull_params`. The default is `--allow-unrelated-histories --squash --strategy=recursive -X theirs`. You have now the full power to control the pull.

**Comment by AndreasAugustin** [comment]
@all-contributors please add @george-gca  for idea
