### ISSUE TITLE
[Bug]: <insert bug description>

### ISSUE THREAD

**Issue by pedrorrivero** [AndreasAugustin/actions-template-sync#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Co-authored email does not match the actual user email, causing conflicts with CLA tools.

### Expected Behavior

```
Co-authored-by: pedrorrivero <pedrorrivero@users.noreply.github.com>
```

### Current Behavior

```
Co-authored-by: pedrorrivero <github-action@actions-template-sync.noreply.github.com>
```

### Possible Solution

Update the coauthored email.

### Additional Information/Context

See here for an example: https://github.com/Qiskit-Extensions/staged-primitives/pull/3

### Template sync version Version

v0.7.3

**Comment by AndreasAugustin** [comment]
Hi @pedrorrivero 

The reason most likely is in the following line within [src/entrypoint.sh](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/entrypoint.sh):
![Screenshot 2023-03-01 at 15 31 01](https://user-images.githubusercontent.com/8027933/222172369-d13a1b7e-e1b3-432e-83f9-bd8bafb53465.png)

Think a change into

```bash
 git config --global user.email "${GITHUB_ACTOR}@users.noreply.${SOURCE_REPO_HOSTNAME}"
```

could possible do the trick.

The contextual issue I see here is that a action is a bot and not a user.

Do you have some more information about your CLA tools?

Maybe a configuration parameter could solve the issue. Do you have some ideas?

**Comment by AndreasAugustin** [comment]
@pedrorrivero would be a parameter to add the git username and the git user email sufficient?

**Comment by pedrorrivero** [comment]
Hey @AndreasAugustin , sorry I have not been able to get back to you before. 

I think your proposal would work, and I do not see any contextual issue because the author will still be the github actions bot as far as I am concerned. The other user and email will be listed as co-authors; which I think is accurate.

Unfortunately I cannot provide more information about the CLA because I do not manage it.

**Comment by AndreasAugustin** [comment]
@pedrorrivero with new release `v0.8.0` you have now 2 new configruation options:
- `git_user_email`
- `git_user_name`
You have now the full freedom to set those variables to your needs.

Related PR: #330

**Comment by AndreasAugustin** [comment]
@all-contributors please add @pedrorrivero  for idea
