### ISSUE TITLE
[Feat]: Have upstream_branch default to the default branch

### ISSUE THREAD

**Issue by ebronson68** [AndreasAugustin/actions-template-sync#338]
### Describe the feature

It would be nice to have the `upstream_branch` default to the default branch in the repository as it is a bit of a pain to change the upstream_branch for different projects that don't follow the typical GitHub Flow branching strategy.

### Use Case

Some of our repositories either don't have a "main" branch or we want the template syncing to create a PR from a "development" branch instead. 

It would save us time if the `upstream_branch` was just set to the default branch for the repository as we wouldn't have to manually set it as an input when calling the action.

### Proposed Solution

Default to the default branch in the repository rather than require the user to override the default, "main", with the name of the branch they normally base their PRs from.

### Acknowledgements

- [x] I may be able to implement this feature request

**Comment by AndreasAugustin** [comment]
> ### Describe the feature
> It would be nice to have the `upstream_branch` default to the default branch in the repository as it is a bit of a pain to change the upstream_branch for different projects that don't follow the typical GitHub Flow branching strategy.
> 
> ### Use Case
> Some of our repositories either don't have a "main" branch or we want the template syncing to create a PR from a "development" branch instead.
> 
> It would save us time if the `upstream_branch` was just set to the default branch for the repository as we wouldn't have to manually set it as an input when calling the action.
> 
> ### Proposed Solution
> Default to the default branch in the repository rather than require the user to override the default, "main", with the name of the branch they normally base their PRs from.
> 
> ### Acknowledgements
> * [x]  I may be able to implement this feature request

Hi @ebronson68 and thank you for your request.

Actually I think it makes sense to have the `upstrream_branch` default to the default branch.
The only issue I see here is that we are breaking backwards compability but we can increase the version to `1.0.0` to make it clear to everyone. Maybe open a discussion to (hopefully) get some further thoughts from the community?

**Comment by AndreasAugustin** [comment]
> ### Describe the feature
> It would be nice to have the `upstream_branch` default to the default branch in the repository as it is a bit of a pain to change the upstream_branch for different projects that don't follow the typical GitHub Flow branching strategy.
> 
> ### Use Case
> Some of our repositories either don't have a "main" branch or we want the template syncing to create a PR from a "development" branch instead.
> 
> It would save us time if the `upstream_branch` was just set to the default branch for the repository as we wouldn't have to manually set it as an input when calling the action.
> 
> ### Proposed Solution
> Default to the default branch in the repository rather than require the user to override the default, "main", with the name of the branch they normally base their PRs from.
> 
> ### Acknowledgements
> * [x]  I may be able to implement this feature request

Hi @ebronson68 and thank you for the suggestion.

The only issue I see here is that this is a breaking change. Because we use semantic versioning with version increase to `1.0.0` we can make it visible to the users.
Maybe starting a discussion (poll) to (hopefully) get some further input of the community could help.

**Comment by ebronson68** [comment]
> > ### Describe the feature
> > It would be nice to have the `upstream_branch` default to the default branch in the repository as it is a bit of a pain to change the upstream_branch for different projects that don't follow the typical GitHub Flow branching strategy.
> > ### Use Case
> > Some of our repositories either don't have a "main" branch or we want the template syncing to create a PR from a "development" branch instead.
> > It would save us time if the `upstream_branch` was just set to the default branch for the repository as we wouldn't have to manually set it as an input when calling the action.
> > ### Proposed Solution
> > Default to the default branch in the repository rather than require the user to override the default, "main", with the name of the branch they normally base their PRs from.
> > ### Acknowledgements
> > 
> > * [x]   I may be able to implement this feature request
> 
> Hi @ebronson68 and thank you for the suggestion.
> 
> The only issue I see here is that this is a breaking change. Because we use semantic versioning with version increase to `1.0.0` we can make it visible to the users. Maybe starting a discussion (poll) to (hopefully) get some further input of the community could help.

Closing this issue for now while we wait for some results from this poll: https://github.com/AndreasAugustin/actions-template-sync/discussions/341

**Comment by AndreasAugustin** [comment]
Reopened because of positive feedback in #341

**Comment by AndreasAugustin** [comment]
@all-contributor please add @ebronson68 for ideas

**Comment by AndreasAugustin** [comment]
@all-contributors please add @ebronson68  for ideas

**Comment by AndreasAugustin** [comment]
@ebronson68 let's go for it 🚀 Do you like to implement the change?

**Comment by ebronson68** [comment]
> @ebronson68 let's go for it 🚀 Do you like to implement the change?

I unfortunately don't think I would be able to. Just let me know if you need my help though.

**Comment by AndreasAugustin** [comment]
Most likely #351 should close this issue. Will do a pre release after merge

**Comment by AndreasAugustin** [comment]
@ebronson68 you can use the prerelease [v1.0.0-draft](https://github.com/AndreasAugustin/actions-template-sync/releases/tag/v1.0.0-draft).
Your request is implemented. Would be nice if you could test it.
sorry that it took long time. Was kinda busy with other stuff.

**Comment by ebronson68** [comment]
> @ebronson68 you can use the prerelease [v1.0.0-draft](https://github.com/AndreasAugustin/actions-template-sync/releases/tag/v1.0.0-draft). Your request is implemented. Would be nice if you could test it. sorry that it took long time. Was kinda busy with other stuff.

Awesome! Yeah, just tested it and it works perfectly! Here's my working test: [![🔄 Sync with .github repository](https://github.com/Andrews-McMeel-Universal/reusable_workflows/actions/workflows/template-sync.yml/badge.svg?branch=DEVOPS-xxx-test-template-sync-update)](https://github.com/Andrews-McMeel-Universal/reusable_workflows/actions/workflows/template-sync.yml)

Thanks for implementing this!

**Comment by AndreasAugustin** [comment]
great that it works! Thanks for testing 🚀 
Will try to do some docs update soon and do a release
