### ISSUE TITLE
[Bug]: repository 'https://github.com/***/' not found

### ISSUE THREAD

**Issue by dotdc** [AndreasAugustin/actions-template-sync#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get an error message when trying to checkout the repository using a custom GitHub PAT.
The PAT used here has the privileges mentionned in the documentation + workflows (rerquired to sync .github).

### Expected Behavior

I would expect the checkout to work.

### Current Behavior

I get this error message:
```
git init
  ::info::set git global configuration
  Updated Git hooks.
  Git LFS initialized.
  ::info::the source repository is located within GitHub.
  github.com
    ✓ Logged in to github.com as dotdc (GITHUB_TOKEN)
    ✓ Git operations for github.com configured to use https protocol.
    ✓ Token: *******************
    
remote: Repository not found.
fatal: repository 'https://github.com/***/' not found
fatal: Needed a single revision
```

### Possible Solution

Use the PAT to checkout instead of the default token.

### Template sync version Version

v1.0.0-draft

**Comment by AndreasAugustin** [comment]
Hi @dotdc thanks for raising the bug. Could you please add an example so that I am able to reproduce the issue?

Maybe also a further remark. Is by any chance your template repository private? In that case when using a `PAT` the target repo also need to be private (https://github.com/AndreasAugustin/actions-template-sync/issues/97#issuecomment-1428648753)

**Comment by dotdc** [comment]
Yes both repositories are private.

I just used the code from the example using PAT. Should be enough to reproduce.

Let me know if it's not the case.

**Comment by dotdc** [comment]
@AndreasAugustin also made a PR with a fix. Let me know if you can both reproduce and test my solution.

**Comment by mpint** [comment]
+1 on this. Seeing the same problem with a private template + PAT with documented permissions
