### ISSUE TITLE
[Bug]: Unable to authenticate to the source repo

### ISSUE THREAD

**Issue by ShivamArora** [AndreasAugustin/actions-template-sync#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm using the action to sync a private template repository. I've created an SSH key, added the public key as a Deploy key to the source repo and added the private key as a secret to the current/target repo.

I've tried using both `ED25519` and `RSA` algorithms with the ssh key. Also have tried changing the source repo path with `https://github.com` as a prefix, `git@gitlab.com:` as a prefix and without any prefix. 

But it seems like the action is unable to authenticate and access the source repo.

### Expected Behavior

The action should be able to authenticate the source repo, compare the two repos and fetch any changes from the source repo to create a PR.

### Current Behavior

I'm encountering the following error within the action logs:
```bash
##[group]ssh setup
::info::prepare ssh
##[endgroup]
##[group]git init
::info::set git global configuration
Updated Git hooks.
Git LFS initialized.
::info::the source repository is located within GitHub.
github.com
  ✓ Logged in to github.com as github-actions[bot] (GITHUB_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
  
##[endgroup]
Load key "/tmp/.ssh/id_rsa_actions_template_sync": error in libcrypto
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

### Template sync version Version

1.1.0

**Comment by AndreasAugustin** [comment]
Hi @ShivamArora and thank you for the question.
Reading your description I see that you try `github` with https and `gitlab` with ssh.
Is your source repo located within GitHub or gitlab? (With ssh the process is kind of the same). Just want to make sure that there is no mix up.

Did you try to clone the repo on your local machine with the specified ssh key?
Are you possibly using a secret for the ssh key (secrets are currently not supported, could be possibly added if there is a feature request).

**Comment by AndreasAugustin** [comment]
Maybe another hint: the source repo path is the path to the repo without the domain.

For GitHub it is:
`<owner>/<repo_name>`

**Comment by ShivamArora** [comment]
Hi @AndreasAugustin , made a typo while writing the description. The repo is on `github` only and is owned by a private Github organization under my account at the moment.

I haven't tried to clone it with the newly created ssh key for this. On my local I use an ssh key tied to my account. However, to integrate this action I created a new one and added it as a deploy key to the source repo.

And yes, I'm using a secret for the ssh key as documented here just with a different secret name: https://github.com/AndreasAugustin/actions-template-sync#2-using-ssh

Plus, I've tried the `<owner>/<repo_name>` approach as well but got the same error.

**Comment by AndreasAugustin** [comment]
Sorry for misspelling on my side. Wanted to check if your secret has a password 🔑

Passwords for ssh keys are not supported (yet)

**Comment by AndreasAugustin** [comment]
Could you pleas try to clone the repo locally to check if it is a general issue?

Remark (for Linux/Unix systems, sorry do not have smith for windows PowerShell, but I guess you need to use `set` instead `export`)


`export GIT_SSH_COMMAND="ssh -i <abs path to key file>"` 

The do the `git clone` (just do an `unset GIT_SSH_COMMAND` afterwards to get back to defaults

**Comment by ShivamArora** [comment]
Just tried cloning after pointing to the newly generated ssh key being used for this workflow. I was able to clone it successfully. @AndreasAugustin

**Comment by ShivamArora** [comment]
HI @AndreasAugustin, I tried out cloning the repo by including another checkout step for the source repo. Turns out the `.git` suffix doesn't need to be included. Also, updated the value of the secret alongwith the full text containing the start and end lines as well which I previously didn't include. The cloning worked after that and so did the cloning within this action.
```
-----BEGIN OPENSSH PRIVATE KEY-----
...
-----END OPENSSH PRIVATE KEY-----
```

It detected the changes, found the conflicts in some files but failed to raise a PR with the following access error:
```bash
  push changes and create PR
  remote: Write access to repository not granted.
  fatal: unable to access 'https://github.com/<Org>/<repo>/': The requested URL returned error: 403
  ```
  
The instructions [here](https://github.com/AndreasAugustin/actions-template-sync#2-using-ssh) explicitly mentioned the key doesn't need write access. Do I need to allow write access to the action somehow? The documentation doesn't contain anything about this.

**Comment by AndreasAugustin** [comment]
@ShivamArora for the push and the PR the github_token and not the ssh key is used.

Do you also set the `github_token` parameter like here:

https://github.com/AndreasAugustin/actions-template-sync/actions/runs/5630235981/workflow

**Comment by AndreasAugustin** [comment]
@ShivamArora I tried to reproduce the issue, but was not able to. See here the action run:
https://github.com/AndreasAugustin/actions-template-sync/actions/runs/5630633212/job/15256821499

resulting into this PR: https://github.com/AndreasAugustin/actions-template-sync/pull/368

Nevertheless the last release introduced another bug which you would have also faced later. Please update to `v1.1.1`  .
Here is the related PR: https://github.com/AndreasAugustin/actions-template-sync/pull/369

**Comment by ShivamArora** [comment]
@AndreasAugustin Thanks for notifying about the update. 

Had to allow the Read and Write permissions along with checking the Allow Github actions to create and approve pull requests under my org.
![image](https://github.com/AndreasAugustin/actions-template-sync/assets/4353659/c8089898-6320-49f8-893f-9fbba0a7e995)

The pull request was raised but to my surprise it removed the changes I had in `package.json` in my current repository which were made after creating the repository from the template repository. Is there any policy around handling merge conflicts in this action?

**Comment by AndreasAugustin** [comment]
The default configuration is `--allow-unrelated-histories --squash --strategy=recursive -X theirs`.
You are able to tweak it with the `git_remote_pull_params`.

Please have a look into `src/sync_template.sh` line 73 if you want to get more into the details.

Currently I don't know why your changes would be reverted.

**Comment by ShivamArora** [comment]
Thanks. I believe it's just discarding my changes in the merge conflicts since the default configuration uses `-X theirs`.

I'm more inclined to use something which would persist the merge conflicts and push them as part of the PR, so I can then checkout and resolve the conflicts locally. But the action would be useful to check if there are any changes in the source template at regular intervals.

I'll spend some time to think of a solution to this.

Meanwhile I'll close the issue as the original issue I was facing is resolved. Thanks for your support @AndreasAugustin .
