### ISSUE TITLE
[Bug]: Actions fails while restoring .templatesyncignore if not already present

### ISSUE THREAD

**Issue by aairey** [AndreasAugustin/actions-template-sync#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When there is no `.templatesyncignore` file present in the child repository yet, but one was added in the template - the template-sync action fails with:

### Expected Behavior

Store the `.templatesyncignore` file from upstream. Ignore errors while restoring the file as it could not be present.

### Current Behavior

The action fails with:
```
restore ignore file
  ::info::restore the ignore file
  ++ git checkout -- .templatesyncignore
  error: pathspec '.templatesyncignore' did not match any file(s) known to git
```

### Steps To Reproduce

1. Create template repo with just a README.md and add template-sync workflow
2. Create a repo from this template
3. Add `.templatesyncignore` in the template
4. Sync child repo with template

### Possible Solution

Ignore errors during file restore.

### Additional Information/Context

Was introduced with #250 and #251 .

### Template sync version Version

1.1.1

**Comment by AndreasAugustin** [comment]
Hi @aairey and thank you very much for the :bug: issue and the nice description with example.
Was able to reproduce the issue with a local test and reading the code logic it is obvious that e.g. `git reset -- .templatesyncignore` is  not working if the file is not present in the history but with your case you hit the `if` condition.

Will provide a fix ASAP (maybe the next days).

**Comment by AndreasAugustin** [comment]
@all-contributors please add @aairey  for bug

**Comment by AndreasAugustin** [comment]
@aairey #378 should fix the issue. Will build a new version soon.
