### ISSUE TITLE
[Bug]: inverse ignore in the .templatesyncignore is not working

### ISSUE THREAD

**Issue by a4s8** [AndreasAugustin/actions-template-sync#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So my corner case is a little different. I need to sync specific files from a template repository.
So I'm configuring the .templatesyncignore like so:

\*
.*
!newfile-1.txt

### Expected Behavior

newfile-1.txt file from the template-repo should appear in the repo which has been created from the template-repo and
all of the rest files and folders be ignored.

### Current Behavior

Everything is being ignored, including newfile-1.txt file

### Additional Information/Context

I've also tried repositioning the content in the .templatesyncignore like so:

!newfile-1.txt
*
.*

No success whatsoever.

### Template sync version Version

v1.1.3

**Comment by AndreasAugustin** [comment]
Hi @a4s8 and thanks for the issue.
Understand your issue.

Think you need to have the content like

```
:!newfile-1.txt
*
```
(add the `:`) related to [gitglossary](https://git-scm.com/docs/gitglossary) (please check the **pathspec** section).

The responsible code part is within `src/sync_template.sh`
![image](https://github.com/AndreasAugustin/actions-template-sync/assets/8027933/5da0dcc4-d388-45be-b474-7ff4c5c72bee)

So the `git reset` cmd is doing the job (https://git-scm.com/docs/git-reset)

Wrote a small local test. At least the test worked as expected.

```bash
mkdir tmp
cd tmp
git init
touch "foo" >> README.md
echo "I want to be tracked with the action" >> newfile-1.txt
git commit [-S] -m "chore: :tada: bootstrap"
echo ":\!newfile-1.txt" >> .templatesyncignore
echo "*" >> .templatesyncignore
git add .
git commit [-S] -m "chore: :see_no_evil: add .templatesyncignore"
echo "will be reverted" >> README.md
echo "won't be reverted" >> newfile-1.txt
git add .
git reset --pathspec-from-file=.templatesyncignore
git status
```

**Maybe a further comment** (possibly not needed):
You need to put the `.templatesyncignore` into the target repository.

**Comment by a4s8** [comment]
First of all, thanks for the fast response!

Second of all, thank you even more for the explanation and helping me with this as I confirm It's working correctly ATM.

I didn't know the semicolon catch and I was only doing it as in a regular .gitignore file.

Learned something new.

**Comment by AndreasAugustin** [comment]
@a4s8 I added a issue to document this a bit more in detail #387
