### ISSUE TITLE
[Bug]: Resync fails with " error: failed to push some refs "

### ISSUE THREAD

**Issue by blu28** [AndreasAugustin/actions-template-sync#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

  When I try to sync my repo, I get this message:

```
  ++ git push --set-upstream origin chore/template_sync_8517761
  To https://github.com/ToughTechs151/ArrayListExample
   ! [rejected]        chore/template_sync_8517761 -> chore/template_sync_8517761 (fetch first)
  error: failed to push some refs to 'https://github.com/ToughTechs151/ArrayListExample'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

### Expected Behavior

Changesets are pulled into the repo.

### Current Behavior

Sync fails with error message.

### Steps To Reproduce

See repo and actions for https://github.com/ToughTechs151/ArrayListExample/actions/runs/7009803183/job/19069044034

### Template sync version Version

AndreasAugustin/actions-template-sync@v0.4.2-draft

**Comment by AndreasAugustin** [comment]
Hi @blu28 and thanks for the bug report and the example.
Sorry for late response, somehow I missed the issue.

Could you please update the action to latest version [v1.1.8](https://github.com/AndreasAugustin/actions-template-sync/releases/tag/v1.1.8)? Related to your example, you are using version `v0.4.2-draft`.

This issue should already be fixed.

Related to [sync_template.sh](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh) (line 47) the action should stop if the branch already exists.

```bash
check_branch_remote_existing() {
  git ls-remote --exit-code --heads origin "${NEW_BRANCH}" || BRANCH_DOES_NOT_EXIST=true

  if [[ "${BRANCH_DOES_NOT_EXIST}" != true ]]; then
    warn "Git branch '${NEW_BRANCH}' exists in the remote repository"
    exit 0
  fi
}

check_branch_remote_existing
```

The branch name is the git ref of the source repository so with a new run it should not update the sync branch within the target repository if there are no new commits within the source repository.

Need to have a closer look.

**Comment by AndreasAugustin** [comment]
@blu28 I see that you have updated the action to `v1.1.8` https://github.com/ToughTechs151/ArrayListExample/actions/runs/7215981214/job/19661294734

Seems your issue is solved?

**Comment by blu28** [comment]
I haven't had a circumstance where it would come up again.

**Comment by AndreasAugustin** [comment]
@blu28 great to hear :+1: 
I am closing the issue. Please reopen if same issue occurs again (or open a new issue)
