### ISSUE TITLE
[Bug]: fatal: unable to access 'https://github.com/***/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by dotdc** [AndreasAugustin/actions-template-sync#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just like mentioned in #357 I get an error message when trying the public repository example.
I think using a custom PAT is mandatory in all cases, even for the checkout part, because that's the token that will be used to open the PR at the end.

### Expected Behavior

I would expect the documentation to have working examples.

### Current Behavior

I get this error message:

```
push changes and create PR
  remote: Permission to ***.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/***/': The requested URL returned error: 403
```

### Template sync version Version

v1.1.8

**Comment by AndreasAugustin** [comment]
Hi @dotdc and thanks for the issue report and #423 

Currently I do not fully understand your issue. Out of my understanding using a PAT is not mandatory when the source (template) repository is public or when using ssh.

All is tested and still used within the current repository:

- public https://github.com/AndreasAugustin/actions-template-sync/actions/runs/7336522469/workflow
- ssh github.com source https://github.com/AndreasAugustin/actions-template-sync/actions/runs/7336522472/workflow
- ssh gitlab source https://github.com/AndreasAugustin/actions-template-sync/actions/runs/7336522470/workflow

Example workflow file for the public case:
![image](https://github.com/AndreasAugustin/actions-template-sync/assets/8027933/6aad4c72-3e36-4c15-8cde-77411722cbc7)

Maybe I do not understand your issue?

**Comment by jellllly420** [comment]
This error is mostly caused by the Github Actions configuration of your repository.

You may go `Settings  > Actions > General > Workflow permissions` of your repo and granted it with r/w permissions.

**Comment by jellllly420** [comment]
Also for this,

> I think using a custom PAT is mandatory in all cases, even for the checkout part, because that's the token that will be used to open the PR at the end.

you can grant the workflow permission to open PR in `Settings  > Actions > General > Workflow permissions` too. I don't think it necessary to use a PAT in your case.

**Comment by AndreasAugustin** [comment]
> This error is mostly caused by the Github Actions configuration of your repository. Your `GITHUB_TOKEN` doesn't have the right permissions to write to your repo.
> 
> You may go `Settings > Actions > General > Workflow permissions` of your repo and grant it with r/w permissions. This may be a fast work-around or you can manually configure the fine-grained permissions of `GITHUB_TOKEN` with a YAML.

@jellllly420 thanks for the hint. Think this is missing within the repository. Should be added into the workflow definition examples (the permission section) 

**Remark** The default configuration for actions is readonly -> definitly need to be added into the documentation section
![image](https://github.com/AndreasAugustin/actions-template-sync/assets/8027933/aaf1c8f2-6624-4ce5-a766-829ac6c2c4d3)

**Comment by AndreasAugustin** [comment]
https://github.com/all-contributors please add @jellllly420  for question

**Comment by AndreasAugustin** [comment]
@/all-contributors please add @jellllly420 for question

**Comment by AndreasAugustin** [comment]
@all-contributors please add @jellllly420 for question

**Comment by dotdc** [comment]
Andreas also found out that you can grant these privileges directly in the workflows files, like in this [PR](https://github.com/dotdc/actions-template-sync/pull/1/files).

Thank you both @jellllly420 and @AndreasAugustin for the explanation and the fix!
