### ISSUE TITLE
[Feat]: Enable this workflow to modify workflow files

### ISSUE THREAD

**Issue by jellllly420** [AndreasAugustin/actions-template-sync#424]
### Describe the feature

Our workflow should be able to modify all workflow files except the one configuring our workflow.

### Use Case

I tried to add this workflow into my repository and got the error below:

```bash
push changes and create PR
   ! [remote rejected] chore/template_sync_<bran_id> -> chore/template_sync_<bran_id> (refusing to allow a GitHub App to create or update workflow `.github/workflows/<workflow_name>.yml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/<user_name>/<repo_name>'
```

This error message was reported before in #176.

Since upstream template repository involving procedure of build or deployment, like a Jekyll theme, are likely to modify their workflow files from time to time, I think we should add the feature described above to enhance the generality of our workflow.

### Proposed Solution

The `checkout` action should be granted **at least** (I'm not sure)  `workflows:write` privilege to enable this feature.

I applied [this advice](https://github.com/orgs/community/discussions/35410#discussioncomment-7645702) and it works well now.

We should tell user to generate a PAT and configure `checkout`  action with this token to add this feature.

### Acknowledgements

- [X] I may be able to implement this feature request

**Comment by AndreasAugustin** [comment]
Hi @jellllly420 and thanks a lot for the request.
indeed currently there is no documentation related to workflow file related changes. The only part is within the [troubleshoot](https://github.com/AndreasAugustin/actions-template-sync#troubleshooting) section.
With a PAT it should be possible to be done. Maybe it is also possible to be done with the `workflow:write` permission. Not sure how long this option is around. It was definitely not  available when the troubleshooting part was added, but that is some time ago :eyes: ..

I think that is definitely worth a try.

About the request to not change the one configuring the worklow:
one possible option could be to add the workflow definition file into [.templatesyncignore](https://github.com/AndreasAugustin/actions-template-sync#ignore-files).

I can think about a use case where teams add the template sync workflow definition files into the template with the intention to sync this file with all target repositories. Currently I do not know if this is working out of a technical perspective, but I guess also worth a try :+1:  What do you think?

**Comment by AndreasAugustin** [comment]
@all-contributors please add @jellllly420 for idea

**Comment by jellllly420** [comment]
> I can think about a use case where teams add the template sync workflow definition files into the template with the intention to sync this file with all target repositories. Currently I do not know if this is working out of a technical perspective, but I guess also worth a try 👍 What do you think?

@AndreasAugustin I think this makes sense though configuring template sync is more like a work of downstream users for me. 

I'll work on the docs work later.
