### ISSUE TITLE
[Feat]: Automatically cleanup older PRs that target the same branch

### ISSUE THREAD

**Issue by kevin-aude** [AndreasAugustin/actions-template-sync#437]
### Describe the feature

When a new PR is created, check if there are older ones that are still open and that target the same branch. If so, delete the older ones since the newer ones would contain the same changes anyway.

### Use Case

If a template is changing often, you may end up with multiple open PRs in the consuming projects. The newer ones also contain the changes from the older ones so it doesn't make sense to keep them all open.

### Proposed Solution

Before creating the new PR, it's possible to use the gh CLI to list open PRs that are targeting the same branch and delete them automatically.

### Acknowledgements

- [X] I may be able to implement this feature request

**Comment by AndreasAugustin** [comment]
@kevin-aude thanks for the feature request. I like it.
Will add some notes into the PR.
