### ISSUE TITLE
[Bug]: Action variables in PR body

### ISSUE THREAD

**Issue by kdeldycke** [AndreasAugustin/actions-template-sync#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Variables in the form of `${...}`, like `${SOURCE_REPO_PATH}` or `${TEMPLATE_GIT_HASH}` are not replaced by their values in the PR's body.

### Expected Behavior

Based on the [default value of the `pr_body` parameter of the action](https://github.com/AndreasAugustin/actions-template-sync/blob/be793c403daf33d61725be1697889ced7a79c896/README.md?plain=1#L242), which reference `${SOURCE_REPO_PATH}` and `${TEMPLATE_GIT_HASH}`, I expect these same variable to be replaced by their values.

### Current Behavior

In my [reuseable workflow](https://github.com/kdeldycke/workflows/blob/2f12fb8c6d04401d1ab364c21215c741d9e89a13/.github/workflows/docs.yaml#L358-L402), I have a job using `actions-template-sync` with a `pr_body` parameter defined as such:

```yaml
          pr_body: >
            Files synced from [`${SOURCE_REPO_PATH}@${TEMPLATE_GIT_HASH}`
            repository](https://github.com/${SOURCE_REPO_PATH}/tree/${TEMPLATE_GIT_HASH}).


            <details><summary><code>Workflow metadata</code></summary>


            > [Auto-generated on run `#${{ github.run_id }}`](${{ github.event.repository.html_url }}/actions/runs/${{
            github.run_id }}) by `${{ github.job }}` job from [`docs.yaml`](${{ github.event.repository.html_url
            }}/blob/${{ github.sha }}/.github/workflows/docs.yaml) workflow.


            </details>
```

The [body of the resulting PR](https://github.com/kdeldycke/awesome-falsehood/pull/177) looks like this:

![Screenshot 2024-03-18 at 17 10 59](https://github.com/AndreasAugustin/actions-template-sync/assets/159718/b83ef0eb-300d-4bfc-abe5-17987e2ed250)

Its markdown is:
```md
Files synced from [`${SOURCE_REPO_PATH}@${TEMPLATE_GIT_HASH}` repository](https://github.com/${SOURCE_REPO_PATH}/tree/${TEMPLATE_GIT_HASH}).

<details><summary><code>Workflow metadata</code></summary>

> [Auto-generated on run `#8329511778`](https://github.com/kdeldycke/awesome-falsehood/actions/runs/8329511778) by `awesome-template-sync` job from [`docs.yaml`](https://github.com/kdeldycke/awesome-falsehood/blob/8f5877a9bf299e33249d5c681c1010a2cfd467b4/.github/workflows/docs.yaml) workflow.

</details>
```

Here you can see that `${{ ... }}` variables are replaced by their values but the `${...}` are not.

### Possible Solution

Maybe I am wrong and I cannot reuse the `${SOMETHING}` format. So I tried an alternative and replaced them by `${{ env.SOMETHING }}` but they reference an empty value, as the `env` is not populated by these variables.

Maybe we should let the action populate the local `env` with its own variables so `${{ env.SOMETHING }}` will work? Not sure how natural this syntax looks like and how much reusing the `env` object is bullet-proof.

### Additional Information/Context

This is a follow up of https://github.com/AndreasAugustin/actions-template-sync/issues/477

Note that the `${...}`/`${{ ... }}` syntax difference [has already been encounter and discussed a bit in another issue](https://github.com/AndreasAugustin/actions-template-sync/issues/467#issuecomment-1974775972).

### Template sync version Version

2.0.0

**Comment by AndreasAugustin** [comment]
Hi @kdeldycke nice find.
#508 will fix the issue (`v2.0.1`).

**One remark:** 
Just one change to the request.
`SOURCE_REPO` is the variable which will be substituted. `SOURCE_REPO_PATH` is an unchanged input variable. You can already use that one in clear text.

**Further remark**
I do not understand why it did not work. Super weird. theoretically it should have worked :ninja: with variables. Also using this e.g. in case for the hooks. But the change is at least fixing the issue. Am now doing manually the substitution.

**Comment by kdeldycke** [comment]
Thanks @AndreasAugustin for the 2.0.1 release.

Just tried that and change `SOURCE_REPO_PATH` to `SOURCE_REPO`. See: https://github.com/kdeldycke/workflows/commit/a1be500e920f5d25f560d49b3dc9b24874111581

But I had the following issue:
```
  To https://github.com/kdeldycke/awesome-falsehood
   ! [remote rejected] sync-awesome-template_8313c9b -> sync-awesome-template_8313c9b (refusing to allow a GitHub App to create or update workflow `.github/workflows/autofix.yaml` without `workflows` permission)
  error: failed to push some refs to 'https://github.com/kdeldycke/awesome-falsehood'
```
See the details at: https://github.com/kdeldycke/awesome-falsehood/actions/runs/8341154880/job/22826633975#step:3:151

That's kind of strange as I always used a specific token with workflow permissions (as documented here: https://github.com/kdeldycke/workflows?tab=readme-ov-file#permissions-and-token).

Can you spot anything strange in the execution logs of the action? Remember that I'm using it as a reuseable workflow so some subtleties might have influenced the process.

**Comment by AndreasAugustin** [comment]
> Thanks @AndreasAugustin for the 2.0.1 release.
> 
> Just tried that and change `SOURCE_REPO_PATH` to `SOURCE_REPO`. See: [kdeldycke/workflows@a1be500](https://github.com/kdeldycke/workflows/commit/a1be500e920f5d25f560d49b3dc9b24874111581)
> 
> But I had the following issue:
> 
> ```
>   To https://github.com/kdeldycke/awesome-falsehood
>    ! [remote rejected] sync-awesome-template_8313c9b -> sync-awesome-template_8313c9b (refusing to allow a GitHub App to create or update workflow `.github/workflows/autofix.yaml` without `workflows` permission)
>   error: failed to push some refs to 'https://github.com/kdeldycke/awesome-falsehood'
> ```
> 
> See the details at: https://github.com/kdeldycke/awesome-falsehood/actions/runs/8341154880/job/22826633975#step:3:151
> 
> That's kind of strange as I always used a specific token with workflow permissions (as documented here: https://github.com/kdeldycke/workflows?tab=readme-ov-file#permissions-and-token).
> 
> Can you spot anything strange in the execution logs of the action? Remember that I'm using it as a reuseable workflow so some subtleties might have influenced the process.


Hi @kdeldycke 
You are using a workflow_call. Therefore AFAIK you need to inject the secrets. Like https://github.com/AndreasAugustin/actions-template-sync/blob/main/.github/workflows/release.yml
 Line 15

Seems you are currently not using your PAT and instead the GitHub secret. Hope the current idea helps. Am on mobile and it is hard to type and search for links/type examples.  https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

**Comment by AndreasAugustin** [comment]
@kdeldycke I wrote a small test to verify my theory. Please check the workflow file here https://github.com/AndreasAugustin/sync-test/blob/main/.github/workflows/outer_call.yml
the called workflow is in the same repository
https://github.com/AndreasAugustin/sync-test/blob/main/.github/workflows/sync.yml

without the `secrets: inherit` like mentioned above I get an error about missing `github_token`. You have a fallback defined in your case so the fallback will take place.

**Comment by AndreasAugustin** [comment]
@kdeldycke  did you have the chance to test the suggestion with `secrets: inherit`?

Further info: #516 is now (finally) released with `v2.1.0`.
Thanks for your patience.

(Sorry for hijacking this issue ticket)

**Comment by kdeldycke** [comment]
> So I am kinda sure you are using the fallback instead of the `PAT`

Yes, it looks that it is the case. The question is *why*?

> Also within the `git init` log part (expand) in your action run https://github.com/kdeldycke/awesome-falsehood/actions/runs/8341154880/job/22826633975#step:3:151 you can see the prefix of the token which is related to the action `GITHUB_TOKEN` and not a `gh_pat`

Yep, that's the definitive proof the workflow is falling back on the local `GITHUB_TOKEN` secret.

So... I updated to latest `v2.1.0` and added the `secrets: inherit` parameter on the calling workflow: https://github.com/kdeldycke/awesome-falsehood/blob/6d629bd5876e6af7cb00f6ec9adfd941ad0ecdba/.github/workflows/docs.yaml#L12-L14

And it works: https://github.com/kdeldycke/awesome-falsehood/actions/runs/8844290657/job/24285909296#step:3:146

Thanks @AndreasAugustin for the help!

Still, I don't understand why my custom `WORKFLOW_UPDATE_GITHUB_PAT` is not picked up. As it was properly available on the local, calling repository since the beginning:
<img width="1128" alt="Screenshot 2024-04-26 at 09 49 03" src="https://github.com/AndreasAugustin/actions-template-sync/assets/159718/082222f2-4af4-44f2-ad6b-366a30d9b6de">

🤔

My guts tells me its because I'm too deep in the inception: I use reuseable workflow to update workflows from the repository implementing the reuseable workflows! 😵‍💫

**Comment by AndreasAugustin** [comment]
> Still, I don't understand why my custom `WORKFLOW_UPDATE_GITHUB_PAT` is not picked up. As it was properly available on the local, calling repository since the beginning

My guess:
if you reuse a workflow you must add the secrets you use into the reusable workflow and explicitly list them within the caller workflow OR use the `secrets: inherit` part.
https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

Thats somehow different between reusable workflows or writing an action.

**Comment by kdeldycke** [comment]
> > Still, I don't understand why my custom `WORKFLOW_UPDATE_GITHUB_PAT` is not picked up. As it was properly available on the local, calling repository since the beginning
> 
> @kdeldycke My guess: if you reuse a workflow you must add the secrets you use into the reusable workflow and explicitly list them within the caller workflow OR use the `secrets: inherit` part. Else the secret is not set within the reusable workflow. https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
> 
> Thats somehow different between reusable workflows or writing an action.

Yes, something like that. But it was my understanding that my strategy was already working as it is not the first time I refer to local secrets. Anyway, I'll continue testing my hypothesis. Thanks @AndreasAugustin for taking the time trying to solve this mystery! 🤗
