### ISSUE TITLE
[Bug]: is_keep_branch_on_pr_cleanup: true results in GitHub syntax error

### ISSUE THREAD

**Issue by kanno41** [AndreasAugustin/actions-template-sync#528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I have `is_keep_branch_on_pr_cleanup: true`, I see the following error in my GitHub Action
<img width="590" alt="template-sync-bug2" src="https://github.com/AndreasAugustin/actions-template-sync/assets/2818651/d500302c-5942-4a16-b33f-4011ab278859">

### Expected Behavior

I expect it to not produce an error

### Current Behavior

See Description

### Possible Solution

It appears to be from this line (-c -c)
https://github.com/AndreasAugustin/actions-template-sync/blob/dbb1da4b844352d31d2565bfcd79f134e1917249/src/sync_template.sh#L204

### Template sync version Version

2.2.0

**Comment by AndreasAugustin** [comment]
@kanno41 fix will be available with next fix version `v2.2.1`. Actually I did not pay attention related to your commit message. The repo automation is using conventional commits (using release-please).
the commit message prefix must be `fix` not bug (sorry, also not documented..).
Will provide the new version ASAP when I am at a PC

**Comment by kanno41** [comment]
Thanks, my brain skipped a beat. I meant to have it as fix.
--
Kenny Harding
