### ISSUE TITLE
[Docs]: No documentation on how to use for Github Enterprise 

### ISSUE THREAD

**Issue by asehrawat24** [AndreasAugustin/actions-template-sync#566]
### Describe the documentation issue

Can someone help me with configuring this for Github Enterprise? I keep getting -   ::info::set git global configuration
  ::info::the source repository is not located within GitHub.
  Error: Process completed with exit code 1.

### Links

https://github.com/AndreasAugustin/actions-template-sync

### Acknowledgements

- [ ] I may be able to submit a pull-request to fix this issue.

**Comment by AndreasAugustin** [comment]
> ### Describe the documentation issue
> Can someone help me with configuring this for Github Enterprise? I keep getting - ::info::set git global configuration ::info::the source repository is not located within GitHub. Error: Process completed with exit code 1.
> 
> ### Links
> https://github.com/AndreasAugustin/actions-template-sync
> 
> ### Acknowledgements
> * [ ]  I may be able to submit a pull-request to fix this issue.

Hi @asehrawat24 and thank you for your issue.
Just for clarification. Is this related GitHub enterprise or GitHub enterprise server? (Unfortunately I am not part of a GitHub enterprise and haven't administrated one so far so hopefully someone within the community has some experience)

Do you possibly have some further debug information?
(E.g. do you get more trace if you retry running the action with debug flag enabled?)

**Comment by asehrawat24** [comment]
How do I change the source to github.mycompany.com instead of github.com

**Comment by AndreasAugustin** [comment]
> How do I change the source to github.mycompany.com instead of github.com

Here you can find a list of all possible parameters: https://github.com/AndreasAugustin/actions-template-sync#action-inputs

For changing the hostname of the source repository please use the `hostname` variable.

**Comment by AndreasAugustin** [comment]
@asehrawat24 have you managed to set it up? 
Do you like to update the documentation?
