### ISSUE TITLE
[Feat]: Add the name of the .templatesyncignore file as a parameter

### ISSUE THREAD

**Issue by TechnicallyJoe** [AndreasAugustin/actions-template-sync#567]
### Describe the feature

Add the name/path of the .templatesyncignore file as a parameter to the action. Default to .templatesyncignore for backwards compatibility.

### Use Case

We're looking into a use case where it would be nice to be able to sync from 2 different repositories but they need their own .templatesyncignore file defined.

### Acknowledgements

- [X] I may be able to implement this feature request

**Comment by AndreasAugustin** [comment]
@all-contributors please add @TechnicallyJoe for ideas and code
