### ISSUE TITLE
Trouble authenticating

### ISSUE THREAD

**Issue by pdrittenhouse** [AndreasAugustin/actions-template-sync#84]
I'm trying to use this action for our team project but can't figure out how to get authenticated.  I either get a 404 error saying that the source repository isn't found (Even though I can access it when I click the link in the console message.  It's a private repo so I'm not sure how that affects it.), or I get a message saying that my access token is missing.  I'm probably just not understanding github actions fully. 

![image](https://user-images.githubusercontent.com/1556730/126087535-526ae5f1-0a5f-4f53-8c77-178830e04c0d.png)

![image](https://user-images.githubusercontent.com/1556730/126088452-894c903a-e4ba-4868-8f69-efc98994d2a8.png)

**Comment by AndreasAugustin** [comment]
Hi @pdrittenhouse . Thank you very much for the issue report.
I try to look into it ASAP.
Currently my time is limited but I try to be fast :)

**Comment by pdrittenhouse** [comment]
> Hi @pdrittenhouse . Thank you very much for the issue report.
> I try to look into it ASAP.
> Currently my time is limited but I try to be fast :)
> 
> Reading your issue description: Private repositories are currently not supported, but it should not be a huge issue to add that feature. Can you please add a feature request?

Will do.  Thanks!

**Comment by AndreasAugustin** [comment]
@pdrittenhouse thanks a lot for the feautre request (#86 ) I'll leave this bug open until it is solved.

Regards and happy coding! :rocket:

**Comment by AndreasAugustin** [comment]
Should be closed with #95 -> `ssh` is implemented, will be part of next release.
`PAT` will be implemented with #97
