### ISSUE TITLE
support private repos with PAT

### ISSUE THREAD

**Issue by AndreasAugustin** [AndreasAugustin/actions-template-sync#97]
**Is your feature request related to a problem? Please describe.**
Soon private repos are supported with SSH (e.q. deployment keys) #95 . Would be nice if also PAT would be supported.

**Describe the solution you'd like**
also PAT supported for AUTHZ for private repos

**Comment by AndreasAugustin** [comment]
This should be solve with #238 (need to check the details, some docs needed)

**Comment by wanisfahmyDE** [comment]
hey @AndreasAugustin I can reproduce the same behaviour with internal repos under a github organization. switching the repos to public works

**Comment by AndreasAugustin** [comment]
Hey @wanisfahmyDE  thank you very much for the test.

**Comment by AndreasAugustin** [comment]
seems several other persons have/had same issue https://github.com/actions/checkout/issues/254

**Comment by AndreasAugustin** [comment]
further analysis:
within source repo one need to go to settings -> actions -> general and enable 
![image](https://user-images.githubusercontent.com/8027933/218569415-89a18526-b5f2-41a6-b10d-612affe61a92.png)
